/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Cliente;
import Logica.DetalleFactura;
import Logica.Habitacion;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Facu
 */
public class Factura extends javax.swing.JInternalFrame {
    
    
    ControladoraVisual unaControladoraVisual = null;
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultComboBoxModel comboCliente = new DefaultComboBoxModel();
    DefaultComboBoxModel comboHabitacion = new DefaultComboBoxModel();
    Verificador unVerificador = new Verificador();

    /**
     * Creates new form Factura
     */
    public Factura(ControladoraVisual unaControladora) {
        initComponents();
        unaControladoraVisual = unaControladora;
        modelo.addColumn("Habitacion");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Subtotal");
        cargarComboCliente();
        cargarComboHabitacion();
    }
    
    public void cargarComboCliente(){
        
        List<Cliente> misClientes = unaControladoraVisual.mostrarClientes();
        
        for (Cliente unCliente : misClientes) {
            comboCliente.addElement(unCliente.getDni());
        }
        
        cmbDNI.setModel(comboCliente);
        
    }
    
    public void cargarComboHabitacion(){
        
        List<Habitacion> misHabitaciones = unaControladoraVisual.mostrarHabitaciones();
        
        for (Habitacion unHabitacion : misHabitaciones) {
            comboHabitacion.addElement(unHabitacion.getId());
        }
        
        cmbHabitacion.setModel(comboHabitacion);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        cmbDNI = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbHabitacion = new javax.swing.JComboBox<>();
        btnFacturar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("FACTURA");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Total:");

        lblTotal.setText("xxxxxxxxxxxx");

        cmbDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDNIActionPerformed(evt);
            }
        });

        jLabel5.setText("DNI:");

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Habitacion", "Descripcion", "Cantidad", "Subtotal"
            }
        ));
        tblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetalle);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Descripcion:");

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Habitacion:");

        cmbHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHabitacionActionPerformed(evt);
            }
        });

        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel10.setText("Monto Hab. :");

        lblMonto.setText("xxx");

        jLabel11.setText("Cliente:");

        lblCliente.setText("xxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCliente)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFacturar)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lblMonto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnBorrar)
                    .addComponent(btnCancelar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotal)
                    .addComponent(btnFacturar)
                    .addComponent(jButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        Double subtotal;
        Double total = 0.0;
        
        int numHabitacion = Integer.parseInt(cmbHabitacion.getSelectedItem().toString());
        
        Habitacion unaHabitacion = unaControladoraVisual.DameLaHabitacion(numHabitacion);
        
        String cadena = Integer.toString(unaHabitacion.getMontoPorNoche());
        
        subtotal = Double.parseDouble(cadena);
        
        Object[] fila = new Object[4];

        fila[0] = numHabitacion;
        fila[1] = txtDescripcion.getText();
        fila[2] = Integer.parseInt(txtCantidad.getText());
        fila[3] = subtotal;

        modelo.addRow(fila);
        
        tblDetalle.setModel(modelo);
        
        txtDescripcion.setText(null);
        txtCantidad.setText(null);
        
        int filas = tblDetalle.getRowCount();

        for (int i = 0; i < filas; i++) {
            total = total + Double.parseDouble(tblDetalle.getValueAt(i, 3).toString());
        }
        
        lblTotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleMouseClicked
        txtDescripcion.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 1).toString());
        txtCantidad.setText(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblDetalleMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        String descripcion = txtDescripcion.getText();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        Double subtotal;
        Double total = 0.0;
        
        int numHabitacion = Integer.parseInt(cmbHabitacion.getSelectedItem().toString());
        
        Habitacion unaHabitacion = unaControladoraVisual.DameLaHabitacion(numHabitacion);
        
        String cadena = Integer.toString(unaHabitacion.getMontoPorNoche());
        
        subtotal = Double.parseDouble(cadena);
        
        tblDetalle.setValueAt(numHabitacion, tblDetalle.getSelectedRow(), 0);
        tblDetalle.setValueAt(descripcion, tblDetalle.getSelectedRow(), 1);
        tblDetalle.setValueAt(cantidad, tblDetalle.getSelectedRow(), 2);
        tblDetalle.setValueAt(subtotal, tblDetalle.getSelectedRow(), 3);
        
        txtDescripcion.setText(null);
        txtCantidad.setText(null);
        
        int filas = tblDetalle.getRowCount();

        for (int i = 0; i < filas; i++) {
            total = total + Double.parseDouble(tblDetalle.getValueAt(i, 3).toString());
        }
        
        lblTotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        Double total = 0.0;
        
        DefaultTableModel modelo2 = (DefaultTableModel) tblDetalle.getModel();
        
        modelo2.removeRow(tblDetalle.getSelectedRow());
        
        tblDetalle.setModel(modelo);
        
        int filas = tblDetalle.getRowCount();

        for (int i = 0; i < filas; i++) {
            total = total + Double.parseDouble(tblDetalle.getValueAt(i, 3).toString());
        }
        
        lblTotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        tblDetalle.clearSelection();
        txtDescripcion.setText(null);
        txtCantidad.setText(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHabitacionActionPerformed
        int id = Integer.parseInt(cmbHabitacion.getSelectedItem().toString());
        
        Habitacion unaHabitacion = unaControladoraVisual.DameLaHabitacion(id);
        
        lblMonto.setText(String.valueOf(unaHabitacion.getMontoPorNoche()));
    }//GEN-LAST:event_cmbHabitacionActionPerformed

    private void cmbDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDNIActionPerformed
        int id = Integer.parseInt(cmbDNI.getSelectedItem().toString());
        
        Cliente unCliente = unaControladoraVisual.DameElCliente(id);
        
        lblCliente.setText(String.valueOf(unCliente.getNombre()) + " " + unCliente.getApellido());
    }//GEN-LAST:event_cmbDNIActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        
        String tipo = txtTipo.getText();
        Double total = Double.parseDouble(lblTotal.getText());
        
        int dni = Integer.parseInt(cmbDNI.getSelectedItem().toString());
        Cliente unCliente = unaControladoraVisual.DameElCliente(dni);
        
        List <DetalleFactura> unosDetalles = new LinkedList();
        
        int filas = tblDetalle.getRowCount();
        
        for (int i = 0; i < filas; i++) {
            
            
            String descripcion = tblDetalle.getValueAt(i, 1).toString();
            int cantidad = Integer.parseInt(tblDetalle.getValueAt(i, 2).toString());
            Double subtotal = Double.parseDouble(tblDetalle.getValueAt(i, 3).toString());
            
            int numHabitacion = Integer.parseInt(tblDetalle.getValueAt(i, 0).toString());
            Habitacion unaHabitacion = unaControladoraVisual.DameLaHabitacion(numHabitacion);
            
            DetalleFactura unDetalleFactura = new DetalleFactura(descripcion, cantidad, subtotal, unaHabitacion);
            
            unosDetalles.add(unDetalleFactura);
            
        }
        
        try {
            unaControladoraVisual.altaFactura(tipo, total, unCliente, unosDetalles);
        } catch (Exception ex) {
            Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnFacturarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbDNI;
    private javax.swing.JComboBox<String> cmbHabitacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
