/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author Facundo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ControladoraVisual unaControladora = new ControladoraVisual();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        ABMCamarero = new javax.swing.JMenuItem();
        ABMCliente = new javax.swing.JMenuItem();
        ABMDepartamento = new javax.swing.JMenuItem();
        ABMFactura = new javax.swing.JMenuItem();
        ABMHabitacion = new javax.swing.JMenuItem();
        ABMMesa = new javax.swing.JMenuItem();
        ABMPlato = new javax.swing.JMenuItem();
        ABMProveedor = new javax.swing.JMenuItem();
        ABMRHabitacion = new javax.swing.JMenuItem();
        ABMRMesas = new javax.swing.JMenuItem();
        ABMRecepcionista = new javax.swing.JMenuItem();
        ABMServicio = new javax.swing.JMenuItem();
        ABMTipo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        jMenu2.setText("ABM");

        ABMCamarero.setText("Camarero");
        jMenu2.add(ABMCamarero);

        ABMCliente.setText("Cliente");
        jMenu2.add(ABMCliente);

        ABMDepartamento.setText("Departamento");
        jMenu2.add(ABMDepartamento);

        ABMFactura.setText("Factura");
        jMenu2.add(ABMFactura);

        ABMHabitacion.setText("Habitacion");
        jMenu2.add(ABMHabitacion);

        ABMMesa.setText("Mesa");
        jMenu2.add(ABMMesa);

        ABMPlato.setText("Plato");
        jMenu2.add(ABMPlato);

        ABMProveedor.setText("Proveedor");
        jMenu2.add(ABMProveedor);

        ABMRHabitacion.setText("RHabitacion");
        jMenu2.add(ABMRHabitacion);

        ABMRMesas.setText("RMesas");
        jMenu2.add(ABMRMesas);

        ABMRecepcionista.setText("Recepcionista");
        jMenu2.add(ABMRecepcionista);

        ABMServicio.setText("Servicio");
        jMenu2.add(ABMServicio);

        ABMTipo.setText("Tipo");
        jMenu2.add(ABMTipo);

        Menu.add(jMenu2);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ABMCamarero;
    private javax.swing.JMenuItem ABMCliente;
    private javax.swing.JMenuItem ABMDepartamento;
    private javax.swing.JMenuItem ABMFactura;
    private javax.swing.JMenuItem ABMHabitacion;
    private javax.swing.JMenuItem ABMMesa;
    private javax.swing.JMenuItem ABMPlato;
    private javax.swing.JMenuItem ABMProveedor;
    private javax.swing.JMenuItem ABMRHabitacion;
    private javax.swing.JMenuItem ABMRMesas;
    private javax.swing.JMenuItem ABMRecepcionista;
    private javax.swing.JMenuItem ABMServicio;
    private javax.swing.JMenuItem ABMTipo;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
