/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author Facundo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ControladoraVisual unaControladora = new ControladoraVisual();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        Reservas = new javax.swing.JMenu();
        ReservaMesa = new javax.swing.JMenuItem();
        ReservaHabitacion = new javax.swing.JMenuItem();
        Presupuesto = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        ABMFactura = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ABMCamarero = new javax.swing.JMenuItem();
        ABMRecepcionista = new javax.swing.JMenuItem();
        ABMDepartamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ABMCliente = new javax.swing.JMenuItem();
        ABMHabitacion = new javax.swing.JMenuItem();
        ABMMesa = new javax.swing.JMenuItem();
        ABMPlato = new javax.swing.JMenuItem();
        ABMProveedor = new javax.swing.JMenuItem();
        ABMServicio = new javax.swing.JMenuItem();
        ABMTipo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        Reservas.setText("Reservas");

        ReservaMesa.setText("Reserva Mesa");
        ReservaMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaMesaActionPerformed(evt);
            }
        });
        Reservas.add(ReservaMesa);

        ReservaHabitacion.setText("Reserva Habitacion");
        ReservaHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaHabitacionActionPerformed(evt);
            }
        });
        Reservas.add(ReservaHabitacion);

        Menu.add(Reservas);

        Presupuesto.setText("Presupuesto");
        Presupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PresupuestoMouseClicked(evt);
            }
        });
        Menu.add(Presupuesto);

        jMenu3.setText("Facturacion");

        ABMFactura.setText("Factura");
        ABMFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMFacturaActionPerformed(evt);
            }
        });
        jMenu3.add(ABMFactura);

        Menu.add(jMenu3);

        jMenu4.setText("RRHH");

        ABMCamarero.setText("Camarero");
        ABMCamarero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMCamareroActionPerformed(evt);
            }
        });
        jMenu4.add(ABMCamarero);

        ABMRecepcionista.setText("Recepcionista");
        ABMRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMRecepcionistaActionPerformed(evt);
            }
        });
        jMenu4.add(ABMRecepcionista);

        ABMDepartamento.setText("Departamento");
        ABMDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMDepartamentoActionPerformed(evt);
            }
        });
        jMenu4.add(ABMDepartamento);

        Menu.add(jMenu4);

        jMenu2.setText("ABM");

        ABMCliente.setText("Cliente");
        ABMCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMClienteActionPerformed(evt);
            }
        });
        jMenu2.add(ABMCliente);

        ABMHabitacion.setText("Habitacion");
        ABMHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMHabitacionActionPerformed(evt);
            }
        });
        jMenu2.add(ABMHabitacion);

        ABMMesa.setText("Mesa");
        ABMMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMMesaActionPerformed(evt);
            }
        });
        jMenu2.add(ABMMesa);

        ABMPlato.setText("Plato");
        ABMPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMPlatoActionPerformed(evt);
            }
        });
        jMenu2.add(ABMPlato);

        ABMProveedor.setText("Proveedor");
        jMenu2.add(ABMProveedor);

        ABMServicio.setText("Servicio");
        ABMServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMServicioActionPerformed(evt);
            }
        });
        jMenu2.add(ABMServicio);

        ABMTipo.setText("Tipo");
        ABMTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMTipoActionPerformed(evt);
            }
        });
        jMenu2.add(ABMTipo);

        Menu.add(jMenu2);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ABMCamareroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMCamareroActionPerformed
        ABMCamarero miABMCamarero = new ABMCamarero(unaControladora); 
        this.Escritorio.add(miABMCamarero);
        miABMCamarero.show();
    }//GEN-LAST:event_ABMCamareroActionPerformed

    private void ABMRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMRecepcionistaActionPerformed
        ABMRecepcionista miABMRecepcionista = new ABMRecepcionista(unaControladora);
        this.Escritorio.add(miABMRecepcionista);
        miABMRecepcionista.show();
    }//GEN-LAST:event_ABMRecepcionistaActionPerformed

    private void ABMClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMClienteActionPerformed
        ABMCliente miABMCliente = new ABMCliente(unaControladora);
        this.Escritorio.add(miABMCliente);
        miABMCliente.show();
    }//GEN-LAST:event_ABMClienteActionPerformed

    private void ABMDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMDepartamentoActionPerformed
        ABMDepartamento miABMDepartamento = new ABMDepartamento(unaControladora);
        this.Escritorio.add(miABMDepartamento);
        miABMDepartamento.show();
    }//GEN-LAST:event_ABMDepartamentoActionPerformed

    private void ABMTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMTipoActionPerformed
        ABMTipo miABMTipo = new ABMTipo(unaControladora);
        this.Escritorio.add(miABMTipo);
        miABMTipo.show();
    }//GEN-LAST:event_ABMTipoActionPerformed

    private void ABMHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMHabitacionActionPerformed
        ABMHabitacion miABMHabitacion = new ABMHabitacion(unaControladora);
        this.Escritorio.add(miABMHabitacion);
        miABMHabitacion.show();
    }//GEN-LAST:event_ABMHabitacionActionPerformed

    private void ABMFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMFacturaActionPerformed
       Factura miFactura = new Factura(unaControladora);
       this.Escritorio.add(miFactura);
       miFactura.show();
    }//GEN-LAST:event_ABMFacturaActionPerformed

    private void ABMMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMMesaActionPerformed
        ABMMesa miABMMesa = new ABMMesa(unaControladora);
        this.Escritorio.add(miABMMesa);
        miABMMesa.show();
    }//GEN-LAST:event_ABMMesaActionPerformed

    private void ReservaMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaMesaActionPerformed
        ReservaMesa miReservaMesa = new ReservaMesa(unaControladora);
        this.Escritorio.add(miReservaMesa);
        miReservaMesa.show();
    }//GEN-LAST:event_ReservaMesaActionPerformed

    private void ABMPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMPlatoActionPerformed
        ABMPlato miABMPlato = new ABMPlato(unaControladora);
        this.Escritorio.add(miABMPlato);
        miABMPlato.show();
    }//GEN-LAST:event_ABMPlatoActionPerformed

    private void ReservaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaHabitacionActionPerformed
        Recepcion miRecepcion = new Recepcion(unaControladora);
        this.Escritorio.add(miRecepcion);
        miRecepcion.show();
    }//GEN-LAST:event_ReservaHabitacionActionPerformed

    private void PresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresupuestoMouseClicked
        Presupuesto miPresupuesto = new Presupuesto(unaControladora);
        this.Escritorio.add(miPresupuesto);
        miPresupuesto.show();
    }//GEN-LAST:event_PresupuestoMouseClicked

    private void ABMServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMServicioActionPerformed
       ABMServicio miABMServicio = new ABMServicio(unaControladora);
       this.Escritorio.add(miABMServicio);
       miABMServicio.show();
    }//GEN-LAST:event_ABMServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ABMCamarero;
    private javax.swing.JMenuItem ABMCliente;
    private javax.swing.JMenuItem ABMDepartamento;
    private javax.swing.JMenuItem ABMFactura;
    private javax.swing.JMenuItem ABMHabitacion;
    private javax.swing.JMenuItem ABMMesa;
    private javax.swing.JMenuItem ABMPlato;
    private javax.swing.JMenuItem ABMProveedor;
    private javax.swing.JMenuItem ABMRecepcionista;
    private javax.swing.JMenuItem ABMServicio;
    private javax.swing.JMenuItem ABMTipo;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Presupuesto;
    private javax.swing.JMenuItem ReservaHabitacion;
    private javax.swing.JMenuItem ReservaMesa;
    private javax.swing.JMenu Reservas;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    // End of variables declaration//GEN-END:variables
}
